#!/bin/bash
#Irá en /etc/X11/Xsession.d
#El nombre no es al azar, debe ser: XXcustom_script, sin extensiones, sino Xsession no lo procesa.

equipo=$(hostname -s)
usuario=$USER
dominio=$(host -d -t CNAME servidor | grep domain | cut -f1 -d".")


#Determinamos que tipo de equipo es en función del facter use. Si no tiene el facter lo consideramos workstation.
tipo="WORKSTATION"
if [ -e /usr/bin/facter ]
then
      use=$(facter | grep ^use | cut -d" " -f3)
      case $use in
           ltsp*) tipo="LTSP"
                          ;;
           work*) tipo="WORKSTATION"
                          ;;
           port*) tipo="PORTATIL"
                          ;;
           *) tipo="WORKSTATION"
                          ;;
      esac
fi

#Si es un LTSP, debemos saber si es profesor, ya que los alumnos tambien hacen login (indirectamente) en el equipo del profesor
#y aparecerían registrados en él.
#OJO: aqui el comparador es =. No usar ==, ya que estos scripts NO los ejecuta bash y el == no funciona.
if [ $tipo = "LTSP" ]
then 
	es_profe=$(id -nG $usuario | grep teachers | wc -l)
	if [ $es_profe -ne 0 ]
	then
	  peticion="http://ldap.$dominio/controlies/init/registro/login?usuario=$usuario&maquina=$equipo&tipohost=$tipo"
	  actualiza=$(wget -q -O - $peticion 2>/dev/null)
	fi
else
    #Si es un PORTATIL además hay que intentar averiguar en que aula está para pasar ese dato.
    if [ $tipo = "PORTATIL" ]
    then
        #Obtiene el nombre del pc del profesor preguntando al servidor de aula por XMLRPC.
        aula=$(python -c "import xmlrpclib; s = xmlrpclib.Server('http://192.168.0.254:6800'); print s.getHostName()" 2> /dev/null)
        #Quita el sufijo y el "-", quedando solo el prefijo.
        aula=${aula%-*}
        peticion="http://ldap.$dominio/controlies/init/registro/login?usuario=$usuario&maquina=$equipo&tipohost=$tipo&aula=$aula"
    else
        peticion="http://ldap.$dominio/controlies/init/registro/login?usuario=$usuario&maquina=$equipo&tipohost=$tipo"    
    fi    
    actualiza=$(wget -q -O - $peticion 2>/dev/null)
fi


