#!/bin/bash

equipo=$(hostname -s)
usuario=$LOGNAME

#Si no hay usuario se sale sin hacer nada
test -z $usuario && exit 0

#Primero comprobamos si estamos dentro del centro educativo y tenemos red, con un timeout de 3 segundos.
ping -c 1 ldap -W 3 > /dev/null 2>&1
if [ $? -eq 0 ]
then
   dominio=$(host -d -t CNAME servidor | grep -e ';servidor\.' | cut -f2 -d".")
   peticion="http://ldap.$dominio/controlies/init/registro/logout?usuario=$usuario&maquina=$equipo"
   actualiza=$(wget -q -O - $peticion 2>/dev/null)
fi
