#!/bin/bash

equipo=$(hostname -s)
usuario=$1
dominio=$(host -d -t CNAME servidor | grep domain | cut -f1 -d".")

peticion="http://ldap.$dominio/controlies/init/registro/logout?usuario=$usuario&maquina=$equipo"
actualiza=$(wget -q -O - $peticion 2>/dev/null)
