#!/bin/sh   

if [ -z "$1" ]; then
    echo "$0: called with no interface" 1>&2
    exit 1;
fi

# Run the right scripts
case "$2" in
    up)
        su root -c "invoke-rc.d controlies-client restart &"
        exit 0
        ;;
    *)
        echo "$0: called with unknown action \`$2'" 1>&2
        exit 0
        ;;
esac
