#!/bin/sh
### BEGIN INIT INFO
# Provides:          controlies
# Short-Description: ControlIES avahi daemon
# Description:       Debian init script for ControlIES
### END INIT INFO
#
# Author:	Manuel Mora Gordillo <manuito at gmail.com>
#                                                                                                                                      

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

NAME=avahiClient
message="controlies avahi daemon"

rundir=/var/run 
pidfile=$rundir/controlies/avahiclient.pid
logfile=/var/log/controlies.log
daemon="/usr/bin/python"
application=/var/web2py/applications/controlies/avahiClient.py

test -x $DAEMON || exit 0
test -r $application || exit 0
rm -rf /tmp/controlies*

. /lib/lsb/init-functions

if [ ! -d /var/run/controlies ]; then
	rm -rf /var/run/controlies
	mkdir -p /var/run/controlies
fi

case "$1" in
    start)
		log_daemon_msg "Starting $message"
		[ ! -f $logfile ] && touch $logfile
		start-stop-daemon --start --quiet --pidfile=$pidfile --make-pidfile --exec $daemon $application &
		log_end_msg 0
		;;
	
    stop)
		log_daemon_msg "Stopping $message"
		start-stop-daemon --stop --quiet --pidfile $pidfile
		rm -rf /tmp/controlies*
		log_end_msg 0
		;;
	
    reload)
    	log_daemon_msg "Reloading $message"
		start-stop-daemon --stop --quiet --signal HUP --pidfile $pidfile &
    	log_end_msg 0
    	;;
    	
    restart|force-reload)
		log_daemon_msg "Restarting $message"
		$0 stop
		sleep 1
		$0 start
		log_end_msg 0
		;;
	*)
		log_success_msg "Usage: $0 {start|stop|restart|force-reload|reload}"
		exit 1
		;;
esac

exit 0
