#!/bin/sh
### BEGIN INIT INFO
# Provides:          controlies
# Short-Description: ControlIES avahi daemon
# Description:       Debian init script for ControlIES
### END INIT INFO
#
# Author:	Manuel Mora Gordillo <manuito at gmail.com>
#                                                                                                                                      

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

NAME=avahiClient
message="controlies avahi/RPC/WebSocket daemon"

rundir=/var/run 
logfile=/var/log/controlies.log
daemon="/usr/bin/python"

pidfile1=$rundir/controlies/RPCServer.pid
application1=/var/web2py/applications/controlies/RPCServer.py

pidfile2=$rundir/controlies/avahiclient.pid
application2=/var/web2py/applications/controlies/avahiClient.py

pidfile3=$rundir/controlies/websocket.pid
application3=/var/web2py/applications/controlies/websocket_messaging.py

pidfile4=$rundir/controlies/syncData.pid
application4=/var/web2py/applications/controlies/syncData.py

test -x $DAEMON || exit 0
test -r $application1 || exit 0
test -r $application2 || exit 0
test -r $application3 || exit 0
test -r $application4 || exit 0
rm -rf /tmp/controlies*

. /lib/lsb/init-functions

if [ ! -d /var/run/controlies ]; then
	rm -rf /var/run/controlies
	mkdir -p /var/run/controlies
fi

case "$1" in
    start)
		log_daemon_msg "Starting $message"
		[ ! -f $logfile ] && touch $logfile
		start-stop-daemon --start --quiet --pidfile=$pidfile1 --make-pidfile --exec $daemon $application1 &
		start-stop-daemon --start --quiet --pidfile=$pidfile2 --make-pidfile --exec $daemon $application2 &
		start-stop-daemon --start --quiet --pidfile=$pidfile3 --make-pidfile --exec $daemon $application3 &
		start-stop-daemon --start --quiet --pidfile=$pidfile4 --make-pidfile --exec $daemon $application4 &
		log_end_msg 0
		;;
	
    stop)
		log_daemon_msg "Stopping $message"
		start-stop-daemon --stop --quiet --pidfile $pidfile1
		start-stop-daemon --stop --quiet --pidfile $pidfile2
		start-stop-daemon --stop --quiet --pidfile $pidfile3
		start-stop-daemon --stop --quiet --pidfile $pidfile4
		rm -rf /tmp/controlies*
		log_end_msg 0
		;;
	
    reload)
    	log_daemon_msg "Reloading $message"
		start-stop-daemon --stop --quiet --signal HUP --pidfile $pidfile1 &
		start-stop-daemon --stop --quiet --signal HUP --pidfile $pidfile2 &
		start-stop-daemon --stop --quiet --signal HUP --pidfile $pidfile3 &
		start-stop-daemon --stop --quiet --signal HUP --pidfile $pidfile4 &
    	log_end_msg 0
    	;;
    	
    restart|force-reload)
		log_daemon_msg "Restarting $message"
		$0 stop
		sleep 1
		$0 start
		log_end_msg 0
		;;
	*)
		log_success_msg "Usage: $0 {start|stop|restart|force-reload|reload}"
		exit 1
		;;
esac

exit 0
