#!/bin/bash

#Quita el -PRO o -pro del final del nombre del ordenador, para determinar
#el nombre del aula
equipo=$(hostname -s)
aula=${equipo%-[Pp][Rr][Oo]}
dominio=$(host -d -t CNAME servidor | grep -e ';servidor\.' | cut -f2 -d".")

#Extrae de ldap la lista de thinclients de ese aula.
thinclients=$(ldapsearch -xLLL -h ldap -b cn=THINCLIENTS,cn=DHCP\ Config,dc=instituto,dc=extremadura,dc=es "cn" | grep -i "cn: $aula-O"  | cut -f2 -d" ")

#Averigua  el nombre del interfaz de la red vlan interna del aula, ya que no tiene por que ser eth0
red_interna=$(ifconfig | grep -B1 192.168 | grep -o "^\w*")

for thinclient in $thinclients 
do
  mac=$(ldapsearch -xLLL -h ldap -b cn=THINCLIENTS,cn=DHCP\ Config,dc=instituto,dc=extremadura,dc=es "cn=$thinclient" "dhcpHWAddress" | grep ethernet | grep -v '00:00:00:00:00:00' | cut -f3 -d " " | tr -d " ")
  echo "Despertando $thinclient con mac $mac"

  /usr/bin/wakeonlan $mac
  /usr/sbin/etherwake -i $red_interna $mac

  #Inserta el thinclient con raton=0 y teclado=0. 
  #              Si en los proximos 5 minutos  arranca el cliente y actualiza raton y teclado, todo OK
  #              Si no, se queda con valor  0-0, lo cual es sintoma de que el equipo no ha podido arrancar o bien está colgado. 
  peticion="http://ldap.$dominio/controlies/init/registro/actualizathinclient?host=$thinclient&raton=0&teclado=0"
  actualiza=$(wget -q -O - $peticion 2>/dev/null)

  sleep 1

done

#Espera 6 minutos
sleep 360 

for thinclient in $thinclients 
do
  peticion="http://ldap.$dominio/controlies/init/registro/checkapagado?host=$thinclient"
  actualiza=$(wget -q -O - $peticion 2>/dev/null)
  sleep 1

done

