#!/bin/bash
#Se ejecuta cada X minutos y comprueba si teclado y/o ratón han cambiado de estado respecto
#al estado anterio. Si es así, envía un mensaje a controlies para reflejar el cambio.
#Nota: solo funciona bien con los dispositivos USB. Si se conecta o desconecta en caliente
#un dispositivo PS/2, normalmente el estado proporcionado por /proc/bus/input/devices no cambia,
#ya que los dispositivos PS/2 no suelen generar eventos en su conexión/desconexión.

equipo=$(hostname -s)
dominio=$(host -d -t CNAME servidor | grep -e .domain -e .ns | cut -f1 -d".")

#En teclados Sweex USB, aparece mouse en devices, aun cuando no haya ratón 
#conectado. Con el filtro grep -v kbd eliminamos esas lineas, para que solo
#coja las corresponden a un ratón real.
raton=$(cat /proc/bus/input/devices  | grep -i mouse | grep -v kbd | wc -l)


#En teclados RML, la cadena es "keykoard" en lugar de "keyboard"
teclado=$(cat /proc/bus/input/devices  | grep -i key[bk]oard | wc -l)

#Valor "1": no detectado. Valor "2": detectado. Valor "0": desconocido, no revisado.
if [ $raton -eq 0 ]
then
   hayraton="1"
else
   hayraton="2"
fi

if [ $teclado -eq 0 ]
then
  hayteclado="1"
else
  hayteclado="2"
fi

#Recupera el estado anterior de teclado y ratón.
if [ -f /tmp/kmwatchdog ]
then
   km_anterior=$(cat /tmp/kmwatchdog)
else
   km_anterior=""   
fi
#Estado actual
km_actual="${hayteclado}${hayraton}"

#Si el estado ha cambiado, manda un aviso para actualizar el thinclient.
if  [ "$km_anterior" != "$km_actual" ]
then

    peticion="http://ldap.$dominio/controlies/init/registro/actualizathinclient?host=$equipo&raton=$hayraton&teclado=$hayteclado"
    actualiza=$(wget -q -O - $peticion 2>/dev/null)

    #Queda el estado actual para la siguiente comprobación.
    echo "${hayteclado}${hayraton}" > /tmp/kmwatchdog

fi

#Si hay un usuario logueado, actualiza el campo logout con la hora actual, por si se apaga
#bruscamente.

haysocket=$(ls -1 /var/run/ldm_socket*  | wc -l)

if [ $haysocket -eq 0 ]
then
  exit 0
fi

if [ -z $LDM_SOCKET ]
then
   LDM_SOCKET=$(ls -1 /var/run/ldm_socket*  | head -1)
else
   exit 0
fi

if [ -z $LDM_SERVER ]
then
   LDM_SERVER=192.168.0.254
else 
   exit 0
fi

#Utiliza el socket ssh creado entre thinclient y servidor para averiguar el login del usuario
LDM_USERNAME=$(ssh -S $LDM_SOCKET $LDM_SERVER "id -un")

if [ -z $LDM_USERNAME ]
then
   exit 0
fi

usuario=$LDM_USERNAME

peticion="http://ldap.$dominio/controlies/init/registro/logout?usuario=$usuario&maquina=$equipo"
actualiza=$(wget -q -O - $peticion 2>/dev/null)

